# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source code
COPY src ./src

# Build the project
RUN npm run build

# Expose ports (none needed for stdio)

# Default command
CMD ["node", "dist/index.js"]
